services:
  postgres:
    image: postgres:16-alpine
    container_name: drive-postgres
    environment:
      POSTGRES_DB: drive_empresarial
      POSTGRES_USER: drive_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - drive-pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: drive-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - drive-minio-data:/data

volumes:
  drive-pgdata:
  drive-minio-data: